/* Native, user-owned permissions and agent library. Never rendered inside an App. */
LaRuche.AppAccess=(function(){
  var esc=LaRuche.Utils.esc, modal=null, config=null, models=[], app=null, catalogue=[], scope='laruche', chain=Promise.resolve();
  function tr(fr,en){return LaRuche.i18n.get()==='fr'?fr:en;}
  function api(path,body){return fetch(LaRuche.API.base+path,{method:body?'POST':'GET',credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined}).then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.error&&d.error.message||'HTTP '+r.status);return d;});});}
  function close(){if(modal){modal.close();modal.remove();modal=null;}}
  function shell(title){
    close();modal=document.createElement('dialog');modal.className='apps-access';
    modal.innerHTML='<header><div><small>LARUCHE</small><h2>'+esc(title)+'</h2></div><button class="apps-btn" data-close aria-label="'+esc(tr('Fermer','Close'))+'">×</button></header><div class="apps-access-body"></div><footer role="status" id="appAccessStatus"></footer>';
    document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=close;modal.addEventListener('click',function(e){if(e.target===modal)close();});modal.showModal();return modal.querySelector('.apps-access-body');
  }
  function status(text,error){var s=document.getElementById('appAccessStatus');if(s){s.textContent=text;s.classList.toggle('error',!!error);}}
  function load(){return Promise.all([api('/api/apps/access'),api('/api/apps'),api('/api/apps/permissions')]).then(function(r){config=r[0].config;models=r[0].models;catalogue=r[2].permissions;return r[1].apps;});}
  function policy(){return config.policies[app.id]||(config.policies[app.id]={principals:{},invokeAgents:[]});}
  function effective(operation){var p=policy();var r=p.principals[scope]||{},base=p.principals.laruche||{};var a=operation==='discover'||operation==='open'?r[operation]:(r.actions||{})[operation];var b=operation==='discover'||operation==='open'?base[operation]:(base.actions||{})[operation];return a==null?(b==null?operation==='discover':b):a;}
  function savePolicy(){
    var body={kind:'policy',appId:app.id,policy:JSON.parse(JSON.stringify(policy()))};status(tr('Enregistrement…','Saving…'));
    chain=chain.catch(function(){}).then(function(){return api('/api/apps/access',body);}).then(function(){status(tr('Droits enregistrés. Chaque nouvel appel est contrôlé.','Permissions saved. Every new call is checked.'));}).catch(function(e){status(e.message,true);});
  }
  function permissionName(id){var p=catalogue.find(function(p){return p.id===id;});return p?(LaRuche.i18n.get()==='fr'?p.titleFr:p.titleEn):id;}
  function rightsRow(operation,title,hint){
    var r=policy().principals[scope]||{},value=operation==='discover'||operation==='open'?r[operation]:(r.actions||{})[operation];
    return '<div class="app-right-row"><span class="app-right-state '+(effective(operation)?'allowed':'denied')+'">'+(effective(operation)?'●':'○')+'</span><div><strong>'+esc(title)+'</strong><small>'+esc(hint||operation)+'</small></div><select data-rule="'+esc(operation)+'" aria-label="'+esc(title)+'">'+[[null,tr('Hériter','Inherit')],[true,tr('Autoriser','Allow')],[false,tr('Refuser','Deny')]].map(function(o){return '<option value="'+String(o[0])+'" '+((value==null?o[0]===null:value===o[0])?'selected':'')+'>'+esc(o[1])+'</option>';}).join('')+'</select></div>';
  }
  function renderRights(host,review){
    var manifest=app.manifest||{},permissions=manifest.permissions||{required:[],optional:[]};
    host.innerHTML='<div class="app-access-summary"><div><strong>'+esc(manifest.name||app.id)+'</strong><p>'+esc(app.id)+' · '+esc(app.activeVersion)+' · '+esc(manifest.publisher&&manifest.publisher.name||'')+'</p></div><span class="apps-state '+(app.enabled?'enabled':'disabled')+'">'+esc(app.enabled?tr('Active','Enabled'):tr('Désactivée','Disabled'))+'</span></div>'+
      '<p class="app-access-explain">'+esc(tr('Les droits ci-dessous concernent ton compte. Le socle du paquet est administré pour toute la ruche. Un guide ou un prompt ne peut pas élargir ces droits.','The permissions below belong to your account. Package capabilities are administered hive-wide. Guides and prompts cannot expand these permissions.'))+'</p>'+
      '<section><h3>'+esc(tr('1. App → LaRuche : capacités du paquet','1. App → LaRuche: package capabilities'))+'</h3><p>'+esc(tr('Déclarées par le développeur. Lis-les avant d’activer le paquet.','Declared by the developer. Review before enabling the package.'))+'</p><div id="packageGrants"></div><button class="apps-btn apps-btn-primary" id="saveAppGrants">'+esc(app.enabled?tr('Appliquer les capacités','Apply capabilities'):tr('Approuver et activer','Approve and enable'))+'</button></section>'+
      '<section><h3>'+esc(tr('2. Agent → App : accès et actions','2. Agent → App: access and actions'))+'</h3><label class="app-scope-label">'+esc(tr('Configurer pour','Configure for'))+' <select id="appPrincipal">'+[{id:'laruche',name:tr('LaRuche · droits par défaut','LaRuche · default permissions')}].concat(config.agents).map(function(a){return '<option value="'+esc(a.id)+'" '+(scope===a.id?'selected':'')+'>'+esc(a.name)+'</option>';}).join('')+'</select></label><p>'+esc(tr('Les agents héritent des droits LaRuche, sauf autorisation ou refus explicite. Vert = autorisé, cercle vide = refusé.','Agents inherit LaRuche permissions unless explicitly allowed or denied. Green = allowed, empty circle = denied.'))+'</p><div id="agentRights">'+rightsRow('discover',tr('Découvrir et lire le guide','Discover and read guide'))+rightsRow('open',tr('Ouvrir une vue','Open a view'))+(manifest.actions||[]).map(function(a){return rightsRow(a.name,a.name,a.description+(a.readOnly?tr(' · lecture déclarée',' · declared read-only'):''));}).join('')+'</div></section>'+
      '<section><h3>'+esc(tr('3. App → Agents : modèles qu’elle peut solliciter','3. App → Agents: models it may invoke'))+'</h3><p>'+esc(tr('Nécessite aussi la capacité agents.invoke ci-dessus. Chaque agent/partie possède son contexte. Ces appels consomment des tokens chez son provider.','Also requires agents.invoke above. Each agent/game has its own context. Calls consume tokens on its provider.'))+'</p><div class="app-agent-grants">'+[{id:'laruche',name:'LaRuche',avatar:'🐝'}].concat(config.agents).map(function(a){return '<label><input type="checkbox" data-invoke="'+esc(a.id)+'" '+(policy().invokeAgents.indexOf(a.id)!==-1?'checked':'')+'> '+esc(a.avatar||'◉')+' '+esc(a.name)+'</label>';}).join('')+'</div><button class="apps-btn" id="openAgentLibrary">'+esc(tr('Bibliothèque d’agents','Agent library'))+'</button></section>'+
      '<details><summary>'+esc(tr('Guide et actions déclarés par le développeur','Developer guide and declared actions'))+'</summary><pre>'+esc(manifest.guide||tr('Aucun guide fourni.','No guide provided.'))+'</pre></details>';
    var grants=host.querySelector('#packageGrants');
    grants.innerHTML=permissions.required.concat(permissions.optional).map(function(id){var required=permissions.required.indexOf(id)!==-1,available=catalogue.some(function(p){return p.id===id;});return '<label class="app-package-grant"><input type="checkbox" value="'+esc(id)+'" '+((app.grantedPermissions||[]).indexOf(id)!==-1||required?'checked ':'')+(!available||required?'disabled':'')+'><span><strong>'+esc(permissionName(id))+'</strong><small>'+esc(id)+' · '+esc(!available?tr('Non disponible','Unavailable'):required?tr('Requise','Required'):tr('Optionnelle','Optional'))+'</small></span></label>';}).join('')||'<p>'+esc(tr('Aucune capacité demandée.','No capabilities requested.'))+'</p>';
    var save=host.querySelector('#saveAppGrants');save.disabled=!LaRuche.Auth.isAdmin();
    save.onclick=function(){var selected=Array.from(grants.querySelectorAll('input:checked')).map(function(i){return i.value;});save.disabled=true;api('/api/apps/'+encodeURIComponent(app.id)+'/enable',{grantedPermissions:selected}).then(function(updated){app=updated;renderRights(host,false);LaRuche.Apps.rescan();status(tr('Capacités appliquées.','Capabilities applied.'));}).catch(function(e){save.disabled=false;status(e.message,true);});};
    host.querySelector('#appPrincipal').onchange=function(){scope=this.value;renderRights(host,false);};
    host.querySelectorAll('[data-rule]').forEach(function(select){var operation=select.dataset.rule,r=policy().principals[scope]||{},v=operation==='discover'||operation==='open'?r[operation]:(r.actions||{})[operation];select.value=v==null?'null':String(v);select.onchange=function(){var p=policy();var r=p.principals[scope]||(p.principals[scope]={actions:{}});var value=this.value==='null'?null:this.value==='true';if(operation==='discover'||operation==='open')r[operation]=value;else{r.actions=r.actions||{};if(value===null)delete r.actions[operation];else r.actions[operation]=value;}renderRights(host,false);savePolicy();};});
    host.querySelectorAll('[data-invoke]').forEach(function(input){input.onchange=function(){var p=policy();p.invokeAgents=p.invokeAgents.filter(function(id){return id!==input.dataset.invoke;});if(input.checked)p.invokeAgents.push(input.dataset.invoke);savePolicy();};});
    host.querySelector('#openAgentLibrary').onclick=library;
    if(review)status(tr('App installée mais inactive : examine les droits avant approbation.','Installed but inactive: review permissions before approving.'));
  }
  function open(id,review){var host=shell(tr('Permissions de l’App','App permissions'));scope='laruche';load().then(function(apps){app=apps.find(function(a){return a.id===id;});if(!app)throw new Error('App not found');if(host.isConnected)renderRights(host,review);}).catch(function(e){status(e.message,true);});}
  function library(){var host=shell(tr('Bibliothèque d’agents','Agent library'));load().then(function(){if(host.isConnected)renderLibrary(host);}).catch(function(e){status(e.message,true);});}
  function renderLibrary(host){
    host.innerHTML='<p class="app-access-explain">'+esc(tr('Une fiche est réutilisable. Les conversations restent séparées par App, agent et identifiant de session. Les agents Apps utilisent uniquement les actions autorisées de cette App.','A profile is reusable. Conversations are isolated by App, agent and session id. App agents use only authorized actions of that App.'))+'</p><div class="app-library-layout"><aside><button class="apps-btn apps-btn-primary" id="newAppAgent">+ '+esc(tr('Créer un agent','Create agent'))+'</button><div id="appAgentList"></div></aside><form id="appAgentForm"></form></div>';
    var list=host.querySelector('#appAgentList');
    config.agents.forEach(function(a){var b=document.createElement('button');b.className='app-agent-card';b.innerHTML='<span>'+esc(a.avatar||'◉')+'</span><div><strong>'+esc(a.name)+'</strong><small>'+esc(a.model)+'</small></div>';b.onclick=function(){agentForm(host,a);};list.appendChild(b);});
    host.querySelector('#newAppAgent').onclick=function(){agentForm(host,null);};agentForm(host,config.agents[0]||null);
  }
  function agentForm(host,source){
    var a=source?JSON.parse(JSON.stringify(source)):{id:crypto.randomUUID(),name:'',avatar:'🎲',personality:'',instructions:'',maxTokens:1024,temperature:0.4};
    var form=host.querySelector('#appAgentForm');
    form.innerHTML='<label>'+esc(tr('Nom','Name'))+'<input name="name" required maxlength="80" value="'+esc(a.name)+'" placeholder="Joueur de dames"></label><label>Avatar <input name="avatar" maxlength="256" value="'+esc(a.avatar)+'" placeholder="🎲"></label><label>'+esc(tr('Provider / modèle','Provider / model'))+'<select name="model" required>'+models.map(function(m,i){return '<option value="'+i+'" '+(m.profile===a.profileId&&m.name===a.model?'selected':'')+'>'+esc(m.profile_name+' / '+m.name)+'</option>';}).join('')+'</select></label><label>'+esc(tr('Personnalité et style','Personality and style'))+'<textarea name="personality" maxlength="2000" rows="2">'+esc(a.personality)+'</textarea></label><label>'+esc(tr('Instructions','Instructions'))+'<textarea name="instructions" maxlength="16384" rows="6">'+esc(a.instructions)+'</textarea></label><div class="app-agent-limits"><label>Max tokens<input name="maxTokens" type="number" min="64" max="8192" value="'+a.maxTokens+'"></label><label>'+esc(tr('Température','Temperature'))+'<input name="temperature" type="number" min="0" max="2" step="0.1" value="'+a.temperature+'"></label></div><div class="app-form-actions"><button class="apps-btn apps-btn-primary" '+(!models.length?'disabled':'')+'>'+esc(tr('Enregistrer','Save'))+'</button>'+(source?'<button type="button" class="apps-btn" id="deleteAppAgent">'+esc(tr('Supprimer','Delete'))+'</button>':'')+'</div><p>'+esc(tr('Les accès se règlent dans Permissions de chaque App, en sélectionnant cet agent. Les clés restent dans les profils providers de LaRuche.','Set access in each App’s Permissions by selecting this agent. Keys stay in LaRuche provider profiles.'))+'</p>';
    form.onsubmit=function(e){e.preventDefault();var values=new FormData(form),m=models[Number(values.get('model'))];if(!m)return;a.name=String(values.get('name'));a.avatar=String(values.get('avatar'));a.personality=String(values.get('personality'));a.instructions=String(values.get('instructions'));a.profileId=m.profile;a.model=m.name;a.maxTokens=Number(values.get('maxTokens'));a.temperature=Number(values.get('temperature'));api('/api/apps/access',{kind:'agent',agent:a}).then(function(r){config=r.config;renderLibrary(host);status(tr('Agent enregistré.','Agent saved.'));}).catch(function(e){status(e.message,true);});};
    var del=form.querySelector('#deleteAppAgent');if(del)del.onclick=function(){if(!window.confirm(tr('Supprimer cet agent et révoquer ses accès ?','Delete this agent and revoke its access?')))return;api('/api/apps/access',{kind:'deleteAgent',agentId:a.id}).then(function(r){config=r.config;renderLibrary(host);}).catch(function(e){status(e.message,true);});};
  }
  return {open:open,library:library};
})();
